apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-deployment
  labels:
    app: fraud-dec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-dec
  template:
    metadata:
      labels:
        app: fraud-dec
    spec:
      containers:
      - name: fraud-dec
        image: 164311333392.dkr.ecr.ap-south-1.amazonaws.com/eks-fraud-det:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: eks-fraud-det-env
        ports:
        - containerPort: 5000


