apiVersion: v1
kind: Service
metadata:
  name: fraud-det-service
spec:
  selector:
    app: fraud-det
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  clusterIP: 10.100.0.6 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
